name: Dasher-rust
version: 0.4.7
slug: dasher-rust
description: Filter websocket events for dashboard entities
url: https://github.com/genehand/ha-apps
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: auto
ports:
  8125/tcp: 8125
ports_description:
  8125/tcp: Port for the proxy server
options:
  ha_host: homeassistant:8123
  transparent: false
schema:
  ha_host: str
  transparent: bool
  log_level: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)?
